name: Windows Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore the application
      run: dotnet restore
      

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
        
    - name: Publish the app
      run: dotnet publish -c $env:Configuration -r win-x64 --sc
      env:
        Configuration: Release


    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Windows Release
        path: ./PixNinja.GUI/bin/Release/net6.0/win-x64/publish/
